x-environment: &common-env
  TZ: "Asia/Tokyo"

services:
  db:
    container_name: go_struct_db
    build:
      context: .
      dockerfile: db.dockerfile
    tty: true
    environment:
      <<: *common-env
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "go_struct_db"
      MYSQL_HOST: go_struct_db
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: go_struct_mysql_data
        target: /var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


volumes:
  go_struct_mysql_data: