# ./.devcontainer/compose.yml
version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ../:/app
      - ./id_rsa:/root/.ssh/id_rsa:ro
    network_mode: host
    environment:
      TZ: Asia/Tokyo

    command: sleep infinity