// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/LeastKIds/go_struct/internal/adapter/router"
)

// Injectors from wire.go:

func InitializeRouter() (router.IRouter, error) {
	iScopes := ProviderScopes()
	iSubRepository := ProviderDummyRepository()
	repository := ProviderRepository(iScopes, iSubRepository)
	iDummyInteractor := ProviderDummyInteractor(repository)
	iDummyHandler := ProviderDummyHandler(iDummyInteractor)
	iSubRouter := ProviderDummyRouter(iDummyHandler)
	iRouter := ProviderRouter(iSubRouter)
	return iRouter, nil
}
